---
# tasks file for fubarhouse.jenkinsjobs

- name: Jenkins Jobs | Clone repository
  git:
    repo: "{{ jenkins_repository }}"
    dest: "{{ jenkins_tempdir }}"
    clone: yes
    update: yes
    force: no

- name: Jenkins Jobs | Remove configured jobs
  file:
    path: "{{ jenkins_jobs_directory }}/{{ item[0].folder }}"
    state: touch
  with_nested:
    - "{{ jenkins_jobs }}"
  loop_control:
    label: "{{ item[0].name }}"
  when: item[0].state == absent

- name: Jenkins Jobs | Copy configured jobs
  copy:
    src: "{{ jenkins_tempdir }}/{{ item[0].folder }}/{{ item[1] }}"
    dest: "{{ jenkins_jobs_directory }}/{{ item[0].folder }}/{{ item[1] }}"
  with_nested:
    - "{{ jenkins_jobs }}"
    - "{{ item[0].files }}"
  loop_control:
    label: "{{ item[0].name }}"
  when: item[0].state == present
