
---
# tasks file for fubarhouse.jenkinsjobs

- name: Jenkins Jobs | Clone/update repository
  git:
    repo: "{{ jenkins_repository }}"
    dest: "{{ jenkins_tempdir }}"
    clone: yes
    update: yes
    force: no

- name: Jenkins Jobs | Remove configured jobs
  file:
    path: "{{ jenkins_directory }}/jobs/{{ item.folder }}"
    state: absent
  with_items:
    - "{{ jenkins_jobs }}"
  when:
    - item.state is defined
    - item.folder is defined
    - item.state == "absent"

- name: Jenkins Jobs | Create directories for jobs
  file:
    path: "{{ jenkins_directory }}/jobs/{{ item.folder }}"
    state: directory
    mode: 0755
    owner: "{{ jenkins_job_owner }}"
    group: "{{ jenkins_job_group }}"
  with_items:
    - "{{ jenkins_jobs }}"
  when:
    - item.state is defined
    - item.folder is defined
    - item.state == "present"

- name: Jenkins Jobs | Copy configured jobs
  copy:
    src: "{{ jenkins_tempdir }}/{{ item.0.folder }}/{{ item.1 }}"
    dest: "{{ jenkins_directory }}/jobs/{{ item.0.folder }}/{{ item.1 }}"
    mode: 0755
    owner: "{{ jenkins_job_owner }}"
    group: "{{ jenkins_job_group }}"
  with_subelements:
    - "{{ jenkins_jobs }}"
    - "{{ files }}"
  when:
    - item.0.state is defined
    - item.0.folder is defined
    - item.1 is defined
    - item.0.state == "present"

- name: Jenkins Jobs | Remove configured files
  file:
    path: "{{ jenkins_directory }}/{{ item.filename }}"
    state: absent
  with_items:
    - jenkins_config_files
  when:
    - jenkins_config_files
    - item.state == "absent"

- name: Jenkins Jobs | Copy configured files
  copy:
    src: "{{ jenkins_tempdir }}/{{ item.filename }}"
    dest: "{{ jenkins_directory }}/{{ item.filename }}"
    mode: 0755
    owner: "{{ jenkins_job_owner }}"
    group: "{{ jenkins_job_group }}"
  with_items:
    - jenkins_config_files
  when:
    - jenkins_config_files
    - item.state == "present"
